name: Reality Gon
favicon: null
layout_spectrum: 0.34179
typography_spectrum: 0.37902
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#bebebe'
    - '#686868'
    - '#ffad01'
  brandStrength: 0.5185659290291369
  lightness: 0.5674786742310971
  saturation: 0.705463478108868
  rhythmicContrast: 0.5926180945243686
purpose: []
