name: Reality Gon
favicon: null
layout_spectrum: 0.43913
typography_spectrum: 0.37902
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#bebebe'
    - '#686868'
    - '#ffad01'
  brandStrength: 0.75
  lightness: 0.125
  saturation: 0.705463478108868
  rhythmicContrast: 0.75
purpose: []
